extends: google
env:
  node: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  no-extra-parens:
    - error
    - all
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
  object-curly-spacing:
    - error
    - always
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  one-var:
    - error
    - initialized: never
      uninitialized: always
  no-console: error
  no-alert: error
  no-debugger: error
  valid-jsdoc: error
  new-parens: off
  eqeqeq: off
  one-var-declaration-per-line: off
  space-infix-ops: off
  no-cond-assign: off
  no-eq-null: off
  no-return-assign: off
  require-jsdoc: off
