extends: standard
parser: typescript-eslint-parser
env:
  node: true
rules:
  no-console: error
  no-warning-comments: warn
  # Temporary switch-offs due to instability of typescript-eslint-parser
  indent: off
  space-before-function-paren: off
  no-undef: off
  no-unused-vars: off
  no-useless-constructor: off
  new-parens: off
  space-infix-ops: off
